In [31]:
import pandas as pd
from ethnicolr import census_ln, pred_census_ln, pred_wiki_ln

In [5]:
airbnb = pd.read_csv('C:/Users/dlsim/Documents/_College/1 UC Davis/4 Senior Year/Spr - STA 160 - Practice in Data Science/160 - Airbnb/AirbnbStudy/airbnb_wdistances.csv')

In [13]:
airbnb.head()
df = pd.DataFrame(airbnb.host_name)

In [18]:
ethn_df = census_ln(df, 'host_name',2010)
print(ethn_df)

           host_name pctwhite pctblack pctapi pctaian pct2prace pcthispanic
0               John    40.98    21.03  21.27   11.17      2.41        3.15
1           Jennifer     60.8    21.93   2.66     (S)       (S)       13.29
2          Elisabeth      NaN      NaN    NaN     NaN       NaN         NaN
3        LisaRoxanne      NaN      NaN    NaN     NaN       NaN         NaN
4              Laura    58.58     6.22   3.72    0.33      1.32       29.83
...              ...      ...      ...    ...     ...       ...         ...
48890        Sabrina      NaN      NaN    NaN     NaN       NaN         NaN
48891        Marisol      NaN      NaN    NaN     NaN       NaN         NaN
48892  Ilgar & Aysel      NaN      NaN    NaN     NaN       NaN         NaN
48893            Taz      NaN      NaN    NaN     NaN       NaN         NaN
48894     Christophe    15.23    78.26   0.58     0.7      1.86        3.37

[48895 rows x 7 columns]

In [22]:
ethn_df.dropna().shape[0]

32652

In [23]:
ethn_df.dropna()

        host_name pctwhite pctblack pctapi pctaian pct2prace pcthispanic
0            John    40.98    21.03  21.27   11.17      2.41        3.15
1        Jennifer     60.8    21.93   2.66     (S)       (S)       13.29
4           Laura    58.58     6.22   3.72    0.33      1.32       29.83
5           Chris    76.06    11.87   3.19    3.47      1.64        3.76
6           Garon    82.44      2.2   6.48     (S)       (S)        7.14
...           ...      ...      ...    ...     ...       ...         ...
48886       Scott    60.21    32.92   0.51    1.18      2.59        2.58
48887       Melki    90.24      (S)    (S)       0      5.49         (S)
48888         Kat     48.7    14.29  30.52     (S)       (S)         3.9
48889     Michael    83.59     8.88   1.95    0.67      1.85        3.06
48894  Christophe    15.23    78.26   0.58     0.7      1.86        3.37

[32652 rows x 7 columns]

In [27]:
def countRows(df):
    df1 = census_ln(df, "host_name")
    df2 = pred_census_ln(df,"host_name")
    df3 = pred_wiki_ln(df, "host_name")
    
    nas1 = df1.dropna().shape[0]
    nas2 = df2.dropna().shape[0]
    nas3 = df3.dropna().shape[0]
    
    all = pd.DataFrame(np.array([["census_ln","pred_census_ln","pred_wiki_ln"],[nas1,nas2,nas3]]),
                                 columns = ["Method","Row Count"])
    return(all)

In [32]:
df1 = census_ln(df, "host_name")
df2 = pred_census_ln(df,"host_name")
df3 = pred_wiki_ln(df, "host_name")

nas1 = df1.dropna().shape[0]
nas2 = df2.dropna().shape[0]
nas3 = df3.dropna().shape[0]

In [33]:
print(nas1,nas2,nas3)

32411 48874 48874

In [35]:
df3

,host_name,race,"Asian,GreaterEastAsian,EastAsian","Asian,GreaterEastAsian,Japanese","Asian,IndianSubContinent","GreaterAfrican,Africans","GreaterAfrican,Muslim","GreaterEuropean,British","GreaterEuropean,EastEuropean","GreaterEuropean,Jewish","GreaterEuropean,WestEuropean,French","GreaterEuropean,WestEuropean,Germanic","GreaterEuropean,WestEuropean,Hispanic","GreaterEuropean,WestEuropean,Italian","GreaterEuropean,WestEuropean,Nordic"
0,John,"GreaterEuropean,British",0.118720,0.008419,0.060675,0.059561,0.004151,0.611506,0.009811,0.028905,0.020061,0.020591,0.023875,0.026158,0.007566
1,Jennifer,"GreaterEuropean,British",0.021046,0.004517,0.009110,0.011712,0.008745,0.800473,0.013227,0.026613,0.042861,0.019961,0.016349,0.022732,0.002655
2,Elisabeth,"GreaterEuropean,Jewish",0.003397,0.001515,0.097884,0.116299,0.072111,0.190527,0.044167,0.195029,0.012824,0.055732,0.054400,0.063075,0.093040
3,LisaRoxanne,"GreaterEuropean,WestEuropean,French",0.006007,0.002943,0.003201,0.001511,0.005558,0.038614,0.007791,0.002592,0.523514,0.001405,0.043668,0.360715,0.002482
4,Laura,"GreaterEuropean,WestEuropean,Hispanic",0.007914,0.005499,0.105290,0.032809,0.015094,0.028093,0.025625,0.029095,0.090565,0.006219,0.468178,0.179910,0.005709
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48890,Sabrina,"GreaterEuropean,WestEuropean,Italian",0.006589,0.008382,0.003764,0.008321,0.018897,0.018180,0.048864,0.024373,0.105586,0.002144,0.286659,0.466496,0.001744
48891,Marisol,"GreaterEuropean,British",0.002167,0.018899,0.067780,0.012073,0.026471,0.452222,0.063440,0.134185,0.072391,0.017284,0.087487,0.039564,0.006037
48892,Ilgar & Aysel,"GreaterEuropean,British",0.000493,0.001352,0.010872,0.076393,0.182625,0.248732,0.015672,0.189909,0.036419,0.010001,0.185225,0.018511,0.023797
48893,Taz,"GreaterAfrican,Muslim",0.219171,0.017838,0.008832,0.014987,0.394269,0.042547,0.032953,0.060238,0.045238,0.015298,0.105234,0.036325,0.007069
48894,Christophe,"GreaterEuropean,British",0.005218,0.001457,0.004846,0.003173,0.013963,0.841382,0.002022,0.006723,0.051299,0.003766,0.012111,0.038588,0.015451